version: '1.0'
name: pipeline-20230516
displayName: pipeline-docker
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-48e0d526
    displayName: docker
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 1c257590-d5fa-013b-f381-2a2bbaa818a0
        tag: streamerzero/md
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify:
          - certificate: a0aa1290-d602-013b-0da7-7aca5f14f71c
            events:
              - success
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: weixin
        strategy:
          retry: '0'
