version: '1.0'
name: pipeline-20230516
displayName: pipeline-docker
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-48e0d526
    displayName: docker
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 1c257590-d5fa-013b-f381-2a2bbaa818a0
        tag: streamerzero/md
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
