name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: streamerzero
          password: ${{ secrets.DOCKER_RW }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: streamerzero/md:latest
