name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Build
      run: docker build . --file Dockerfile --tag streamerzero/md:latest
      
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: streamerzero
        password: ${{ secrets.DOCKER_RW }}

    - name: Docker Push
      run: docker push streamerzero/md:latest
